[package]
name = "ojun_b64"
version = "0.1.0"
edition = "2018"
authors = ["Ojun<jun.shima256@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seahorse = "0.7.1"

